### ISSUE TITLE
Warnings after install

### ISSUE THREAD

**Issue by prathers** [xperseguers/t3ext-image_autoresize#64] opened 2022-05-27 17:03 UTC
I get three PHP Warnings after install, when running the configuration in EM:

`Core: Error handler (BE): PHP Warning: Undefined array key "title" in /var/www/html/private/typo3/sysext/backend/Classes/Form/Container/FlexFormSectionContainer.php line 82`

`Core: Error handler (BE): PHP Warning: Undefined array key "title" in /var/www/html/private/typo3/sysext/backend/Classes/Form/Container/OuterWrapContainer.php line 71`

`Core: Error handler (BE): PHP Warning: Undefined property: Causal\ImageAutoresize\Controller\ConfigurationController::$retUrl in /var/www/html/private/typo3conf/ext/image_autoresize/Classes/Controller/ConfigurationController.php line 228`

Env: DDEV, PHP v8.0, TYPO3 v11.6.10

**Comment by xperseguers** [comment] 2022-10-21 15:37
> `Core: Error handler (BE): PHP Warning: Undefined array key "title" in /var/www/html/private/typo3/sysext/backend/Classes/Form/Container/FlexFormSectionContainer.php line 82`

I can't reproduce. Tried with an existing config, or with the default one that comes right after a fresh install. I suspect the configuration you have is somehow broken and missing that key, is it possible?

> `Core: Error handler (BE): PHP Warning: Undefined array key "title" in /var/www/html/private/typo3/sysext/backend/Classes/Form/Container/OuterWrapContainer.php line 71`

Can't reproduce either. I'm with TYPO3 v11.5.17 (btw you wrote you are using v11.6.10, but it doesn't exist, you must have thought v11.5.10). Possibly fixed in core in the mean time?

> `Core: Error handler (BE): PHP Warning: Undefined property: Causal\ImageAutoresize\Controller\ConfigurationController::$retUrl in /var/www/html/private/typo3conf/ext/image_autoresize/Classes/Controller/ConfigurationController.php line 228`

This has been fixed in October 2021 with 02fe1d54

**Closed** 2023-12-11 14:33 UTC
