### ISSUE TITLE
Scheduler crashes

### ISSUE THREAD

**Issue by vmans** [xperseguers/t3ext-image_autoresize#80] opened 2023-07-21 14:57 UTC
TYPO3 12.4.3 / PHP8.1 / ext 2.2.0

Scheduler crashes when trying to add a new task.

**Comment by tmay-px** [comment] 2023-08-24 07:32
I can confirm this issue for TYPO3 12.4.5

`"Fatal error: Declaration of Causal\ImageAutoresize\Task\fakeSchedulerModuleController::addMessage($message, $severity = TYPO3\CMS\Core\Messaging\FlashMessage::OK) must be compatible with TYPO3\CMS\Scheduler\Controller\SchedulerModuleController::addMessage(TYPO3\CMS\Backend\Template\ModuleTemplate $moduleTemplate, string $message, TYPO3\CMS\Core\Type\ContextualFeedbackSeverity $severity = TYPO3\CMS\Core\Type\ContextualFeedbackSeverity::OK): void in /image_autoresize/Classes/Task/BatchResizeAdditionalFieldProvider.php on line 168"`

**Comment by pulponair** [comment] 2023-09-04 14:46
Confirmed

**Comment by jackermann** [comment] 2023-10-05 07:52
I also confirm the error

**Comment by andreashurst** [comment] 2023-10-05 08:42
TYPO3 v12 use this:
protected function addMessage(ModuleTemplate $moduleTemplate, string $message, ContextualFeedbackSeverity $severity = ContextualFeedbackSeverity::OK): void
    {
        $moduleTemplate->addFlashMessage($message, '', $severity);
    }
    
and this is not compatible with:
class fakeSchedulerModuleController extends \TYPO3\CMS\Scheduler\Controller\SchedulerModuleController
{
    public function addMessage($message, $severity = FlashMessage::OK)
    {
        parent::addMessage($message, $severity);
    }
}

**Comment by xperseguers** [comment] 2023-10-08 16:02
What do you think of rewriting the whole scheduler task as a Symfony command instead?

**Comment by tobiasgraeber** [comment] 2023-10-27 18:11
Duplicate of https://github.com/xperseguers/t3ext-image_autoresize/issues/70 ?

**Comment by cepheiVV** [comment] 2023-11-25 04:48
Made a pull request that fixes the method signature of the `addMessage` method.
The scheduler backend module won't throw a fatal error with this change.

**Comment by xperseguers** [comment] 2023-12-09 10:00
Please test https://github.com/xperseguers/t3ext-image_autoresize/tree/bugfix/scheduler-80

**Comment by ErHaWeb** [comment] 2023-12-11 13:49
I can confirm that it works in TYPO3 12.4.7 with the bugfix branch. Thank you @xperseguers

**Closed** 2023-12-11 14:31 UTC
